apiVersion: v1
kind: Service
metadata:
  name: flask-weather-service
spec:
  type: NodePort
  selector:
    app: flask-weather
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
