name: Trivy Scan Docker Hub Image

on:

  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy scan on Docker Hub image
        run: |
          trivy image --scanners --severity HIGH,CRITICAL --exit-code 1 bijuthottathil/flask-weather-api:latest
       
         
