name: Docker Image Vulnerability Scan

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Trivy Vulnerability Scan
        run: |
          DOCKER_IMAGE="bijuthottathil/flask-weather-api:latest" # Replace with the exact tag if needed
          TRIVY_VERSION="1.0"
          FAIL_ON="HIGH,CRITICAL"

          echo "Scanning Docker image: $DOCKER_IMAGE"


      - name: Run Trivy Vulnerability Scan
        run: docker run --rm alpine/git:latest --version

          echo "Scanning Docker image:"

