name: Docker Image Vulnerability Scan

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: Run Trivy Vulnerability Scan
        run: |
          IMAGE_NAME="aquasecurity/trivy:latest"
          TRIVY_VERSION="latest" # You can pin a specific version if needed
          FAIL_ON="HIGH,CRITICAL"

          echo "Scanning Docker image: $IMAGE_NAME"
          docker run --rm \
            aquasecurity/trivy:$TRIVY_VERSION \
            image --exit-code 1 --severity "$FAIL_ON" "$IMAGE_NAME"
