name: Docker Image Vulnerability Scan with Clair

on:
  workflow_dispatch:

jobs:
  scan-with-clair:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull bijuthottathil/flask-weather-api:1.0

    - name: Install clairctl (CLI for Clair)
      run: |
        curl -L https://github.com/quay/clair/releases/latest/download/clairctl-linux-amd64 -o clairctl
        chmod +x clairctl
        sudo mv clairctl /usr/local/bin/

    - name: Start Clair locally (if needed)
      run: |
        docker network create clairnet || true
        docker run -d --name db --network clairnet -e POSTGRES_PASSWORD=password -e POSTGRES_DB=clair -e POSTGRES_USER=clair postgres:14
        docker run -d --name clair --network clairnet \
          -e CLAIR_DATABASE_CONNECTION_STRING=postgres://clair:password@db:5432/clair?sslmode=disable \
          -p 6060-6061:6060-6061 quay.io/projectquay/clair:latest


    - name: Configure clairctl
      run: |
        echo "clair:" > .clairctl.yml
        echo "  uri: http://localhost:6060" >> .clairctl.yml
        echo "  health_uri: http://localhost:6061/health" >> .clairctl.yml

    - name: Scan the image
      run: |
        clairctl report bijuthottathil/flask-weather-api:1.0  --format table

    - name: Upload scan report
      if: always()
      run: |
        clairctl report bijuthottathil//flask-weather-api:1.0 --format json > clair-report.json
        cat clair-report.json
